### ISSUE TITLE
Pop_OS 21.04 New launcher

### ISSUE THREAD

**Issue by supernoi** [dracula/gtk#129] opened 2021-07-15 07:48 UTC
The active option has a strange color in the new version.
I'm sorry, I'm not sure how to explain, looking at the image I think it's easier to understand.

Thanks.

![image](https://user-images.githubusercontent.com/121292/125749606-6d4176bd-fafc-4643-ae0f-5c2730e59a20.png)

**Comment by sartoriusrex** [comment] 2021-07-16 14:30
This is due to the recent update with Pop OS using COSMIC. They updated their program launcher.  It will take some time for the ecosystem to catch up, including for the maintainers of this theme.

Subscribed to any changes in this thread.

Thanks for your support, maintainers!

**Comment by EliverLara** [comment] 2021-12-14 22:14
Hi, I'm sorry for the very late response, this seems to be an issue with the way that 'Pop-OS' determinate if a theme is light or dark, and according to this clasification they apply a custom css style (wich is hard to overwrite) located in /usr/share/gnome-shell/extensions/pop-shell@system76.com, so with this in mind the most feasible solution is to add -dark to the end of the theme folder name.

**Comment by piotrowskiadam** [comment] 2021-12-19 20:35
My Pop!_OS launcher looks nice without any tweaking. 
![Pop OS laucher](https://user-images.githubusercontent.com/55131509/146689935-4987307a-eb53-4ea6-801c-d4419cecfc97.png)


Is this issue to be closed?
PS
I'm thinking however of raising an issue for the new app drawer they released with 21.10 as it looks hard to read with black text on dark background.

**Comment by sartoriusrex** [comment] 2021-12-20 09:45
@EliverLara 

> the most feasible solution is to add -dark to the end of the theme folder name.

While hacky, I can confirm that this solution works.

@supernoi in the folder `/usr/share/themes` is the list of themes that POP_OS can apply. I recursively copied the theme I wanted to a new folder, appending '-dark' to it.

i.e. 

```
sudo cp -r Dracula Dracula-dark
```

**Comment by sartoriusrex** [comment] 2021-12-20 09:47
@piotrowskiadam I think this issue can be closed.

Thank you @EliverLara for maintaining the project. It's pretty sweet.

**Closed** 2022-01-06 21:20 UTC
